### ISSUE TITLE
Get recurring amount

### ISSUE THREAD

**Issue by andrekutianski** [WHMCS/sample-gateway-module#1]
I am developing a module for recurring payments and need to know what are the parameters to this transaction method.

Thanks

**Comment by mattpugh** [comment]
Hello, we don't have documentation or code samples available for this at the current time but we will see what we can do.

**Comment by imzers** [comment]
Hi WHMCS, did this issue resoved? I am experience with this problem too, for development recurring payment with our local payment-gateway, need to know how to identify recurring payment from **paymentmodule_link($params)**
