### ISSUE TITLE
More than one payment gateway in one plugin

### ISSUE THREAD

**Issue by dbrax** [WHMCS/sample-gateway-module#19]
Is it possible to put more than one payment gateway on a single module ??

**Comment by jokerrs** [comment]
It is, you can manipulate with a form which one needs to be populated in the admin area. And you can create the HTML form with a select input that will choose between multiple gateways. 

For example, you can make a 
```html
<select name="payment-method" id="payment-method">
  <option value="bank1">Bank 1</option>
  <option value="bank2">Bank 2</option>
  <option value="bank3">Bank 3</option>
</select>
```
With some javascript which one will automatically make a form or hidden input for every bank.

**Comment by dbrax** [comment]
This is great will work on this thank you very much.
