### ISSUE TITLE
App & Integration installation

### ISSUE THREAD

**Issue by KangLeian** [WHMCS/sample-gateway-module#24]
![image](https://github.com/WHMCS/sample-gateway-module/assets/62584211/e82a581a-81cb-4e8c-9da4-74ce85b25833)
Hi, I want to ask where should I put the code for the name and description like on the image above. I've used meta data but it still not showing.

here is the metadata
```
function duitkupop_MetaData()
{
  return array(
    'DisplayName' => 'Duitku Payment Gateway Module',
    'APIVersion' => '1.0',
    'DisableLocalCredtCardInput' => true,
    'TokenisedStorage' => true,
  );
}
```

Need Help with this one, Thanks.

**Comment by josesoaresif** [comment]
I think what you want to achieve is done using the whmcs.json file. Follow the documentation [link](https://developers.whmcs.com/advanced/json-file/)
as for where you place that file, I believe you need to place it in /modules/gateways/<your_gateway_module_name>/whmcs.json

**Comment by KangLeian** [comment]
Hi @josesoaresif thank you for your answer.
So actually, currently our modules are /modules/gateways/<file_plugins.php>
From your explanation, I need to move and change the file structures to /modules/gateways/<gateway_folder>/<file_plugins.php>
Is this right?
The question is, is this should be applied to the callback file or IPN?
Because the current callback is on /modules/gateways/callback/<file_callback.php>
Should it be  /modules/gateways/callback/<gateway_folder>/<file_callback.php> ?
Or what I need to just add the new folder as like name of my gateways and add the file whmcs.json?

**Comment by KangLeian** [comment]
Hi @josesoaresif ,
I have tried like this
![image](https://github.com/WHMCS/sample-gateway-module/assets/62584211/a4ba79a5-ab9d-48ce-a363-254c44a96e70)
It still has no luck. There is no change on the apps & integrations modules page.

**Comment by josesoaresif** [comment]
Your structure looks correct.
Maybe it is related to the contents of the whmcs.json file.
You need to set the name of your payment method in the name property, and also set the correct category "payments".
For example, this should work for your module:

```
{
    "schema": "1.0",
    "type": "whmcs-gateways",
    "name": "duitkupop",
    "license": "MIT",
    "category": "payments",
    "description": {
        "name": "duitkupop - this is just a description, it can be anything",
        "tagline": "My tagline",
        "long": "My long description",
        "features": [
			"My first feature",
			"My second feature"
        ]
    },
    "logo": {
        "filename": "logo.png"
    },
    "support": {
        "support_url": "https:\/\/support.com",
        "docs_url": "https:\/\/docs.com"
    },
    "authors": [
        {
            "name": "My Author Name",
            "homepage": "https:\/\/myhomepage.com"
        }
    ]
}
```

If you were to add the logo.png you can place it in the same folder.

**Comment by KangLeian** [comment]
Hi @josesoaresif ,

My `whmcs.json` was like this before
![image](https://github.com/WHMCS/sample-gateway-module/assets/62584211/5f4845ae-2727-48ab-a5d9-80c8c86b6799)

It seems not to have much difference, and when I change `whmcs.json` with your code and add the logo file. It works. It seems the logo is a required file.
It looks like this now.
![image](https://github.com/WHMCS/sample-gateway-module/assets/62584211/453b3953-f1b4-4000-b46a-be75a5d747d2)


Thank you for your help @josesoaresif
