### ISSUE TITLE
Is possible $params['duedate']?

### ISSUE THREAD

**Issue by mauriciogofas** [WHMCS/sample-gateway-module#3]
Hello,
thanks for sample gateway!
Is possible get the invoice due date via internal api? Like include $params['duedate']?

**Comment by mattpugh** [comment]
The invoice due date is not a parameter that is automatically passed into payment gateway modules at this time. However you are provided with the `invoiceid` parameter and can then use the Invoice model to lookup the due date. Please refer to https://classdocs.whmcs.com/7.8/WHMCS/Billing/Invoice.html for the Invoice model docs.
