### ISSUE TITLE
Url 404

### ISSUE THREAD

**Issue by ghost** [WHMCS/sample-gateway-module#4]
https://github.com/WHMCS/sample-gateway-module/blob/3bc90195edf7a6041cdbb753dd46f51796e42d45/modules/gateways/gatewaymodule.php#L283 https://developers.whmcs.com/payment-gateways/subscription-management/

**Comment by mattpugh** [comment]
It appears public documentation for subscription management was planned but never completed. I have opened case DOCS-6894 internally to look at getting this addressed.
