### ISSUE TITLE
checkCbTransID() Return 505 (Internal Error) for First Time

### ISSUE THREAD

**Issue by imzers** [WHMCS/sample-gateway-module#5]
Im  just developing plugin payment with  local payment-gateway.
While payment gateway doing First IPN Callback, script stopped by **checkCbTransID($transactionId)** ($transactionId get from payment-gateway - unique payment identification)
But while payment-gateway doing Another IPN Callback for the same **$invoiceId** it was OK and running as expected.

Could you please check for this bugs? Im sure it was bugs from WHMCS, because im trying to manual set static $transactionId for **new $invoiceId** always stopped by 500 error-code header.

Imusing WHMCS v.7.23 thank you so much

**Comment by mattpugh** [comment]
I can confirm there are no known bugs with the checkCbTransID() function at this time.

If you continue to experience issues, please open a ticket with our support team.

**Comment by vipera7** [comment]
Hello, I'm experiencing some issue with the function. It failed randomly on the function. What the code behind ? Any possibility to use API ?

**Comment by Schiocco** [comment]
I confirm the same bug. This function crashes the server.
