### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by tssge** [WHMCS/sample-gateway-module#6]
https://github.com/WHMCS/sample-gateway-module/blob/3bc90195edf7a6041cdbb753dd46f51796e42d45/modules/gateways/gatewaymodule.php#L283

Link on this line is not working / does not exist.

**Comment by JuraseQ** [comment]
up.
Same issue. It looks like after cancel subscription gatewayname_cancelSubscription is not working. I put activity log as first action and nothing happened. Is this really up to date?

**Comment by mattpugh** [comment]
This is a duplicate of #4
